name: Update KBO Data

on:
  schedule:
    - cron: "5 0,4,9,14 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install libs
        run: |
          pip install pandas numpy requests lxml html5lib beautifulsoup4

      - name: Run script
        run: python update_kbo_data.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add data_raw/2026_kbo_official/*.csv || true

          if git diff --cached --quiet; then
            echo "no changes"
          else
            git commit -m "auto update kbo data"
            git push
          fi
